
BEGIN_TEST("Simple get and put test");

CONST_DOUBLE((1));
CONST_DOUBLE((2));

WRITE_INST(CONSTANT, 1);
WRITE_BYTE(0, 1);
WRITE_INST(NEWREF, 1);

WRITE_INST(DUP, 1);

WRITE_INST(CONSTANT, 2);
WRITE_BYTE(1, 2);
WRITE_INST(PUTREF, 2);

WRITE_INST(GETREF, 3);
WRITE_INST(ABORT, 3);
WRITE_BYTE(0, 3);

VERIFY_STACK(1);
VERIFY_FRAMES(0);
VERIFY_NUMBER(2);

END_TEST();