// Test the various numeric operations and capabilities of the VM.

BEGIN_TEST("Addition tests")

CONSTANT(TEST_DOUBLE_VAL(1.2))
CONSTANT(TEST_DOUBLE_VAL(3.4))
CONSTANT(TEST_DOUBLE_VAL(5.6))

WRITE_INST(CONSTANT, 123)
WRITE_BYTE(0, 123)
WRITE_INST(CONSTANT, 123)
WRITE_BYTE(1, 123)
WRITE_INST(DOUBLE_ADD, 123)

WRITE_INST(ABORT, 123)
WRITE_BYTE(0, 123)

VERIFY_FRAMES(0);
VERIFY_STACK(1);
VERIFY_NUMBER((1.2 + 3.4))

END_TEST();

BEGIN_TEST("Division tests")

CONSTANT(TEST_DOUBLE_VAL(1.2))
CONSTANT(TEST_DOUBLE_VAL(3.4))
CONSTANT(TEST_DOUBLE_VAL(5.6))

WRITE_INST(CONSTANT, 123)
WRITE_BYTE(0, 123)
WRITE_INST(CONSTANT, 123)
WRITE_BYTE(1, 123)
WRITE_INST(DOUBLE_ADD, 123)

WRITE_INST(CONSTANT, 123)
WRITE_BYTE(2, 123)
WRITE_INST(DOUBLE_DIV, 123)
WRITE_INST(DOUBLE_NEG, 123)
WRITE_INST(ABORT, 123)
WRITE_BYTE(0, 123)

VERIFY_FRAMES(0);
VERIFY_STACK(1);
VERIFY_NUMBER(-5.6 / (1.2 + 3.4))

END_TEST()